### ISSUE TITLE
Quickstart function does not run locally.

### ISSUE THREAD

**Issue by MrMaxRoss** [GoogleCloudPlatform/cloud-functions-emulator#101]
### Description

I'm trying to run the [Quickstart](https://cloud.google.com/functions/docs/quickstart) function locally but getting an error.

Here's the function:

```
exports.helloWorld = function helloWorld (event, callback) {
    console.log(`My Cloud Function: ${event.data.message}`);
    callback();
};
```
### Steps to reproduce
`functions deploy helloWorld --trigger-http`
`functions call helloWorld --data='{"message":"Hello, World"}'`

This yields the following trace:
```
ExecutionId: a9655fc6-1beb-428e-a85c-cfdfd98c1812
Error: TypeError: Cannot read property 'message' of undefined
    at helloWorld (/Users/xxxx/dev/gcf_hello_world/index.js:8:49)
    at app.use.err (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/src/supervisor/worker.js:114:11)
    at Layer.handle [as handle_request] (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:317:13)
    at /Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:275:10)
    at app.use (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/src/supervisor/worker.js:86:7)
    at Layer.handle [as handle_request] (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/xxxx/npm/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/router/index.js:317:13)
```

I tried specifying the payload in a file and invoking the function with --file but got the same result.

**Comment by jmdobry** [comment]
The function in the Quickstart is not a foreground (HTTP) function, it's a background function (i.e. triggered by Cloud Storage, Cloud Pub/Sub, etc.). HTTP functions have different signatures than background functions.

If you want to use `--trigger-http` then you need to change the function to something like this:

```js
/**
 * Responds to any HTTP request that can provide a "message" field in the body.
 *
 * @param {Object} req Cloud Function request context.
 * @param {Object} res Cloud Function response context.
 */
exports.helloWorld = function helloWorld (req, res) {
  if (req.body.message === undefined) {
    // This is an error case, as "message" is required
    res.status(400).send('No message defined!');
  } else {
    // Everything is ok
    console.log(req.body.message);
    res.status(200).end();
  }
};
```

**Comment by james-woods** [comment]
Is it possible to test background functions with the emulator?
