### ISSUE TITLE
Error when attempting npm install

### ISSUE THREAD

**Issue by dcatoday** [GoogleCloudPlatform/cloud-functions-emulator#107]
### Description

I'm running the install on a work computer (Windows Machine).  I have the proxy set up and am able to install all other packages that I attempt to.  I'm running node 6.9.5 and npm 4.4.4

OUTPUT:
```
> grpc@1.2.4 install C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.2.4/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.2.4 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\sxudma\\.npm-home\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\sxudma\\.npm-home\\node_modules\\@google-cloud\\functions-emulator\\node_modules\\grpc\\src\\node\\extension_binary\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\sxudma\\.npm-home\\node_modules\\@google-cloud\\functions-emulator\\node_modules\\grpc\\src\\node\\extension_binary"
gyp ERR! cwd C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\sxudma\.npm-home\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\sxudma\\.npm-home\\node_modules\\@google-cloud\\functions-emulator\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Users\sxudma\.npm-home\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\src\node\extension_binary' (1)
npm WARN Error: EPERM: operation not permitted, lstat 'C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, lstat 'C:\Users\sxudma\.npm-home\node_modules\@google-cloud\functions-emulator\node_modules\grpc\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'lstat',
npm WARN   path: 'C:\\Users\\sxudma\\.npm-home\\node_modules\\@google-cloud\\functions-emulator\\node_modules\\grpc\\node_modules\\node-pre-gyp\\node_modules\\npmlog\\node_modules\\gauge\\node_modules\\string-width\\node_modules\\is-fullwidth-code-point\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.2.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.2.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sxudma\AppData\Roaming\npm-cache\_logs\2017-05-18T14_38_19_752Z-debug.log
```

### Steps to reproduce

```
npm install -g @google-cloud/functions-emulator
```

Thanks!

**Comment by jmdobry** [comment]
I [opened a bug on grpc](https://github.com/grpc/grpc/issues/11239) to track why the pre-built binaries aren't available, but in the meantime I'll look into upgrading the version of grpc used by the Emulator.

**Comment by jmdobry** [comment]
Hi @dcatoday can you try again (referencing [Installing the Emulator](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Installation)) and let me know how it goes?

I recommend doing:

1. `npm uninstall -g @google-cloud/functions-emulator`
1. `npm install -g @google-cloud/functions-emulator`

**Comment by jmdobry** [comment]
Closing do to inactivity, feel free to comment back here with more information to move forward on this issue.
