### ISSUE TITLE
Error when running functions start

### ISSUE THREAD

**Issue by TomDeVito** [GoogleCloudPlatform/cloud-functions-emulator#109]
### Description

On mac, running functions start produces the following: (nothing in the log file)

```
Starting Google Cloud Functions Emulator...
ERROR: Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (x/src/github.com/x/cloud-functions-emulator/src/cli/controller.js:660:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Steps to reproduce

 Emulator Version      │ 1.0.0-alpha.19

Thanks!

**Comment by jmdobry** [comment]
How did you install the Emulator? How did you install Node.js?

**Comment by jmdobry** [comment]
@TomDeVito friendly ping, are you still running into issues? Can you provide more information?

**Comment by wdumlao** [comment]
I ran into this issue. My initial install of the emulator was working. Then for some odd reason it started to cause issues where it wouln't start.

What do you get when you do `functions logs read`? If you're getting EACCESS issues to the functions/logs directry you have an issue with permissions. So ake sure your current user has access to this folder.

If you fixed the issue above and or don't have that issue and the logs tell you you can't access .functions.json. You also need to make sure you have permission to access the files under:
/Users/<YOURUSER>/.config/configstore/@google-cloud/functions-emulator/.functions.json

I hope this helps.

**Comment by jmdobry** [comment]
Closing do to inactivity, feel free to comment back here with more information to move forward on this issue.

**Comment by mwalkerwells** [comment]
Just ran into this same issue... 1.0.0-alpha.22 node v6.11.1 Chrome 61

This happened after trying to debug in Chrome V8 debugger.

```
mwalkerwells:didi mwalkerwells$ functions start
Starting Google Cloud Functions Emulator...
ERROR: Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:654:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

```
2017-07-19T16:27:30.222Z - info: Execution took 60022 ms, finished with status: 'crash'
2017-07-19T16:27:30.224Z - error: uncaughtException: Can't set headers after they are sent. date=Wed Jul 19 2017 09:27:30 GMT-0700 (PDT), pid=7663, uid=0, gid=0, cwd=/usr/local/lib/node_modules/@google-cloud/functions-emulator, execPath=/usr/local/bin/node, version=v6.11.1, argv=[/usr/local/bin/node, /usr/local/lib/node_modules/@google-cloud/functions-emulator, --bindHost=localhost, --grpcPort=8009, --host=localhost, --timeout=20000, --verbose=false, --useMocks=false, --logFile=/usr/local/lib/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log, --restPort=8008, --supervisorPort=8010, --tail=false], rss=49782784, heapTotal=47030272, heapUsed=30643392, external=821661, loadavg=[2.43017578125, 2.6552734375, 2.7861328125], uptime=89028
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:256:15)
    at ProxyServer.Supervisor._proxy.on (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/supervisor/supervisor.js:97:12)
    at ProxyServer.emit (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/eventemitter3/index.js:144:27)
    at ClientRequest.proxyError (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:156:18)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketCloseListener (_http_client.js:285:9)
2017-07-19T16:27:30.233Z - error: Function worker killed by signal: SIGTERM
```

This happens before any requests are sent...I _think_ this is the same error that I was debugging in the debugger when I _did_ send a request. Also, I cannot find any child processes to kill to start with a clean state...

**Comment by mwalkerwells** [comment]
@jmdobry Not sure if this is still on your radar...

**Comment by mwalkerwells** [comment]
Oh interesting... Running with ``sudo`` works

```
mwalkerwells:didi mwalkerwells$ sudo functions start
Password:
Starting Google Cloud Functions Emulator...
Google Cloud Functions Emulator STARTED
┌───────────┬───────────┬─────────┬──────────────────────────────────────────────────────────┐
│ Status    │ Name      │ Trigger │ Resource                                                 │
├───────────┼───────────┼─────────┼──────────────────────────────────────────────────────────┤
│ DEPLOYING │ helloHttp │ HTTP    │ http://localhost:8010/didi-service/us-central1/helloHttp │
└───────────┴───────────┴─────────┴──────────────────────────────────────────────────────────┘
```

Why is that?

**Comment by jmdobry** [comment]
Probably because of how your Node.js installation is set up. Typically, in my experience, needing to use `sudo` indicates a problem with the Node.js installation/permissions, as you should not need to use `sudo`. I recommend using [nvm](https://github.com/creationix/nvm) to manage your Node.js installation

**Comment by kmleow** [comment]
To add to what @jmdobry has said.

The suggested fix is to change the NPM Global directory to somewhere outside a folder that requires root.
The official doco of NPM: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by metacoding** [comment]
I faced two problems for starting functions emulator on my mac that I bring them here with the solution that worked for me. Hope it helps and save your time:

1- The first error shown on screen 
```
$  functions start
Starting Google Cloud Functions Emulator...
ERROR: Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:650:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```
and from functions logs:
```
$  functions logs read
Warning: You're using Node.js v10.9.0 but the Google Cloud Functions runtime is only available in Node.js 6 and Node.js 8. Therefore, results from running emulated functions may not match production behavior.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Object.readLogLines (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:33:39)
    at Controller.getLogs (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:462:10)
    at Object.exports.handler (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/src/cli/commands/logs/read.js:58:14)
    at Object.runCommand (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:1014:30)
    at Object.runCommand (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:195:96)
    at Object.parseArgs [as _parseArgs] (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:1014:30)
    at Object.parse (/Users/mehrantm/.nvm/versions/node/v10.9.0/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:542:25)
```
To fix this I switched the node to an older version by `nvm use` command: 
```
$  nvm use 6.11.5
Now using node v6.11.5 (npm v3.10.10)
```
then I get this error when issued the command `functions start`:
```
$  functions start
Starting Google Cloud Functions Emulator...
ERROR: Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:650:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```
and this is what I saw in logs:
```
functions logs read
    at new ConfigAdapter (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/model/functions.js:41:23)
    at new Functions (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/model/functions.js:134:22)
    at Object.exports.functions (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/model/index.js:22:34)
    at new Emulator (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/emulator/emulator.js:27:29)
    at Object.main (/Users/mehrantm/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/emulator/main.js:120:20)2018-08-29T23:05:19.031Z - error: uncaughtException: EACCES: permission denied, open '/Users/mehrantm/.config/configstore/@google-cloud/functions-emulator/.functions.json'
You don't have access to this file.
```
as you see it was a permission issue in accessing my user to the emulator config folder.
the solution was easy. you need to go to ~/.config/configstore/@google-cloud/functions-emulator folder and remove all json files.

so the next time I entered `functions start` it started working.
here is the output when it successfully runs:

```
$  functions start
Starting Google Cloud Functions Emulator...
Google Cloud Functions Emulator STARTED
No functions deployed ¯\_(ツ)_/¯. Run functions deploy --help for how to deploy a function.
```
