### ISSUE TITLE
Not working with latest stable version of node

### ISSUE THREAD

**Issue by stevebingsoo** [GoogleCloudPlatform/cloud-functions-emulator#110]
### Description

Warning: You're using Node.js v7.10.0 but Google Cloud Functions only supports v6.9.1.
Error: The module '/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/extension_binary/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

### Steps to reproduce

functions start

Thanks!

**Comment by jmdobry** [comment]
You must have installed the emulator, then upgraded node, then tried to start the emulator.

To fix:

1. Uninstall the emulator
1. Install the emulator

**Comment by stevebingsoo** [comment]
OK I uninstalled (npm uninstall -g @google-cloud/functions-emulator) and reinstalled.  Here's what I get now when I run the functions deploy command mentioned in the Google Actions tutorial (https://developers.google.com/actions/get-started/deploy-fulfillment):

Warning: You're using Node.js v7.10.0 but Google Cloud Functions only supports v6.9.1.
ERROR: Error: Cannot read property '1' of null
    at Request._callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/google-auth-library/lib/transporters.js:100:13)
    at Request.self.callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)

**Comment by jmdobry** [comment]
Hi @stevebingsoo can you try again (referencing [Installing the Emulator](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Installation)) and let me know how it goes?

I recommend doing:

1. `npm uninstall -g @google-cloud/functions-emulator`
1. `npm install -g @google-cloud/functions-emulator`

**Comment by senthilkumar06** [comment]
I get the same problem,
the log I get is as follows,

```
ERROR: Error: Cannot read property '1' of null
    at Request._callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/google-auth-library/lib/transporters.js:100:13)
    at Request.self.callback (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```
I'm using Node v6.9.1 as mentioned.

Can you help me fixing this.
Thank you

**Comment by jmdobry** [comment]
I'm pushing 1.0.0-alpha.21 which should hopefully fix this issue, and at the least reveal what may have been causing it.
