### ISSUE TITLE
Wrong module version expected

### ISSUE THREAD

**Issue by HarvsG** [GoogleCloudPlatform/cloud-functions-emulator#111]
```
$ functions start
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
I am getting this error. Running a nvm 6.9.1
Infact even `functions --help` causes the same error

**Comment by scionwest** [comment]
I am getting this same error now as well.

```
PS C:\Users\Sully> node --version
v6.9.1
PS C:\Users\Sully> functions start
ERROR: (gcloud.info) Name expected [*HERE* 'value(config.project)'].
Enter a projectId to get started: projectId:
error:   Invalid input for projectId
Enter a projectId to get started: projectId:  foo-id-here
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Sully\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules
\grpc\src\node\src\grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by HarvsG** [comment]
I fixed the error. I think it was because I had Installed the @google-cloud module with sudo. So I sudo uninstalled it then reinstalled it without sudo and it worked.

**Comment by jmdobry** [comment]
This error also happens when you install a npm package that has native extensions with one version of Node.js, and then you switch to a different version of Node.js without re-installing the package.

The fix:

```
npm uninstall -g @google-cloud/functions-emulator
npm install -g @google-cloud/functions-emulator
```

**Comment by HarvsG** [comment]
That may also explain it as I started a virtual environment as google cloud functions required version 6.9.1

**Comment by jasonpolites** [comment]
@jmdobry We should create an FAQ with issues like this

**Comment by jmdobry** [comment]
I've updated the [Emulator installation instructions](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Installation) with troubleshooting info and Node.js setup recommendations.

**Comment by 3thanZ** [comment]
Hi @jmdobry 
If we cannot run the functions emulator as sudo, do you have any recommendations on how to get this to work in docker? If I recall correctly docker commands are run as sudo
