### ISSUE TITLE
Emulator crashes unpredictably

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#115]
### Description

I don't have a specific repro for this, but it *seems* to be related to timeout of the function.   I've noticed it happening when I update the function code while the emulator is running.  Perhaps while a function is being executed?

The entire emulator crashes and needs to be started again

```
2017-06-07T04:09:55.664Z - info: Execution took 60002 ms, finished with status: 'timeout'

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/node_modules/express/lib/response.js:256:15)
    at Timeout.req.functionTimeout.setTimeout [as _onTimeout] (/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/src/supervisor/supervisor.js:192:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)2017-06-07T04:09:55.670Z - error: uncaughtException: Can't set headers after they are sent. date=Tue Jun 06 2017 21:09:55 GMT-0700 (PDT), pid=14573, uid=501, gid=20, cwd=/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator, execPath=/Users/Jason/.nvm/versions/node/v6.9.1/bin/node, version=v6.9.1, argv=[/Users/Jason/.nvm/versions/node/v6.9.1/bin/node, /Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator, --bindHost=localhost, --grpcPort=8009, --host=localhost, --timeout=20000, --verbose=false, --useMocks=false, --logFile=/Users/Jason/.nvm/versions/node/v6.9.1/lib/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log, --restPort=8008, --supervisorPort=8010, --tail=false], rss=62623744, heapTotal=38678528, heapUsed=31470896, loadavg=[1.4619140625, 1.4716796875, 1.4970703125], uptime=1374280
```

**Comment by atrauzzi** [comment]
Seeing this as well.  I seem to have to restart the emulator every time I change my code.

**Comment by jmdobry** [comment]
I recently pushed 1.0.0-alpha.21, can you see if it works better for you? @atrauzzi Can you provide reproduction steps?

**Comment by atrauzzi** [comment]
Will do.

**Comment by wdumlao** [comment]
I have the latest 1.0.0-alpha.21 and I'm getting this error as well. Do you need to restart the emulator everytime you make any changes to the functions file?

**Comment by atrauzzi** [comment]
Just tried my function that likes to crash again today.  Seems to definitely be able to take down the whole google functions emulator with it.

Regardless of how/what my function is doing, not sure it should be able to do this.

http://github.com/atrauzzi/protoculture-google-cloud-functions

**Comment by atrauzzi** [comment]
Could it be that the emulator crashes whenever it times out?

```
2017-06-25T19:52:56.188Z - info: Execution took 60005 ms, finished with status: 'timeout'
2017-06-25T19:52:56.196Z - info: Execution took 60013 ms, finished with status: 'crash'

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:730:10)
    at ServerResponse.send (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:256:15)
    at ProxyServer.Supervisor._proxy.on (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\src\supervisor\supervisor.js:97:12)
    at ProxyServer.emit (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\eventemitter3\index.js:144:27)
    at ClientRequest.proxyError (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:156:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:730:10)
    at ServerResponse.send (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:256:15)
    at ProxyServer.Supervisor._proxy.on (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\src\supervisor\supervisor.js:97:12)
    at ProxyServer.emit (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\eventemitter3\index.js:144:27)
    at ClientRequest.proxyError (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:156:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketCloseListener (_http_client.js:334:9)2017-06-25T19:52:56.232Z - error: uncaughtException: Can't set headers after they are sent. date=Sun Jun 25 2017 14:52:56 GMT-0500 (Central Daylight Time), pid=3952, uid=null, gid=null, cwd=C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google
-cloud\functions-emulator, execPath=C:\Program Files\nodejs\node.exe, version=v7.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator, --bindHost=localhost, --grpcPort=8009, --host=localhost, --timeout=20000, --verbose=false, --
useMocks=false, --logFile=C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\logs\cloud-functions-emulator.log, --restPort=8008, --supervisorPort=8010, --tail=false], rss=58781696, heapTotal=36982784, heapUsed=30325752, external=96491, loadavg=[0, 0, 0], uptime=330719.445
0547
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:730:10)
    at ServerResponse.send (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\express\lib\response.js:256:15)
    at ProxyServer.Supervisor._proxy.on (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\src\supervisor\supervisor.js:97:12)
    at ProxyServer.emit (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\eventemitter3\index.js:144:27)
    at ClientRequest.proxyError (C:\Users\atrauzzi\AppData\Roaming\npm\node_modules\@google-cloud\functions-emulator\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:156:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
```

**Comment by jmdobry** [comment]
@wdumlao

> Do you need to restart the emulator everytime you make any changes to the functions file?

No, by default it watches deployed files for changes and reloads the function for you.

**Comment by atrauzzi** [comment]
@jmdobry - There seems to be an issue whenever a function times out.  Such that it takes the entire server down with it.

**Comment by robertaparri** [comment]
I am running into the same issue, the emulator worked until it timed out today. Now when I use 'functions start' it gives me:
>Starting Google Cloud Functions Emulator...
ERROR: Error: Emulator crashed! Check the log file...
    at ChildProcess.child.on (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:654:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by jmdobry** [comment]
@robertaparri Can you provide me with some steps so I can reproduce the error you're seeing?

**Comment by lakin32** [comment]
Hi!

I'm firebase user with using firebase functions and local emulator.
(My firebase-tools version is `3.9.1`)

i don't know why this error occured to me.

sometimes, i didn't change any code. Functions worker was killed with `SIGTERM` signal.
 
```
[FIREBASE] info: Worker for api closed due to file changes.
[FIREBASE] error: Function worker killed by signal: SIGTERM
```

and few minute ago, suddenly return to my app with http code 500 and crashed with `SIGTERM`

```
[FIREBASE] info: Execution took 1617 ms, finished with status: 'crash'
[FIREBASE] error: Function worker killed by signal: SIGTERM
```

after 60s correctly dead emulator with this log.

```
[FIREBASE] info: Execution took 60001 ms, finished with status: 'timeout'
[FIREBASE] Error: Can't set headers after they are sent.
[FIREBASE]     at ServerResponse.setHeader (_http_outgoing.js:371:11)
[FIREBASE]     at ServerResponse.header (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:730:10)
[FIREBASE]     at ServerResponse.send (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:170:12)
[FIREBASE]     at ServerResponse.json (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:256:15)
[FIREBASE]     at Timeout.req.functionTimeout.setTimeout [as _onTimeout] (C:\Users\DELL\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator\src\supervisor\supervisor.js:192:14)
[FIREBASE]     at ontimeout (timers.js:386:14)
[FIREBASE]     at tryOnTimeout (timers.js:250:5)
[FIREBASE]     at Timer.listOnTimeout (timers.js:214:5)
```

One difference point is that it doesn't die if you do not call the firebase API.
I don't understand. 😢

**Comment by lakin32** [comment]
@jmdobry 

! think this ![code](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/893efc5b53c1cca9007e0813ca36959a41859ed0/src/supervisor/supervisor.js#L90-L106) is a bit suspicious.

When an error occurs while the function is running, `http-proxy` of `supervisor.js` is handled by the `error` event type.

The code obviously responds to the client with 500, but does not handle the request timeout through `clearTimeout(req.functionTimeout);`.

and after 60s, emulator is down... 😃 

Sorry, i'm not good at English

**Comment by ebidel** [comment]
Seeing this over on a project that we recently released on the Chrome team. 

Our Puppeteer module downloads a local version of Chrome into a folder named `.local-chromium`. For some reason, the file watching causes the worker to stop and crashes the emulator. Running with `functions inspect` first _does_ work, b/c we don't hit [this code path](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/115). 

To repro, copy this package.json:

```
{
  "dependencies": {
    "firebase-admin": "^5.2.0",
    "firebase-functions": "^0.6.1",
    "puppeteer": "^0.9.0"
  }
}
```

then call `functions call getVersion`:

```js
const functions = require('firebase-functions');
const puppeteer = require('puppeteer');

exports.getVersion = functions.https.onRequest((req, res) => {
  puppeteer.launch().then(browser => {
    browser.version().then(ver => { // crash
      res.status(200).send(ver);
      browser.close();
    });
  });
});
```

-> `{"error":{"code":500,"status":"INTERNAL","message":"function crashed","errors":["socket hang up"]}}`
 
Again, debugging with `node --inspect` works:
```
functions start
functions inspect
functions call getVersion
```

**Comment by RedShift1** [comment]
Having the same problem here.

**Comment by ebidel** [comment]
@jmdobry Should file watching on `node_modules` be ignored? The emulator should only reload user code.

**Comment by jmdobry** [comment]
The addition of the `--watch true/false` and `--watchIgnore <filepatterns...>` to `functions start` should help here, as well as some stability improvements to the supervisor. `watchIgnore` ignores `node_modules` by default now.

However, comment back on this issue if you still encounter the same issue.

**Comment by sampl** [comment]
Here are the docs that specify how to end an HTTP function https://firebase.google.com/docs/functions/http-events#terminate_http_functions

I had this issue while returning from inside an async function, but returning the response seemed to work...

Bad:
`exports.myFunction = functions.https.onRequest((request, response) => {
  db.collection("myCollection").get().then( snapshot => {
    // do something with snapshot
    response.status(200).send(`Successfully got collection`)
    return // doesn't return response
  }).catch( error => {
    response.status(500).send(`Error getting collection: ${error}`)
    // no return
  })
})`

Good:
`exports.myFunction = functions.https.onRequest((request, response) => {
  db.collection("myCollection").get().then( snapshot => {
    // do something with snapshot
    return response.status(200).send(`Successfully got collection`)
  }).catch( error => {
    return response.status(500).send(`Error getting collection: ${error}`)
  })
})`

**Comment by ssbothwell** [comment]
I wrote a stripped down function to show just where the crash is happening:
```
  app.get('/account/:uId/persona/:pId/test', (req, res) => {
    const uid = req.params.uId;
    const pid = req.params.pId;
    
    admin.firestore()
      .collection('tripp-users')
      .doc(uid)
      .get()
      .then((succ) => res.status(204).send("success"))
      .catch(err => res.status(500).send("failure"))
  });
```

**Comment by rajaraodv** [comment]
This reproduces this 100% of the times: https://github.com/applitools/TAU-firebase-debug


```

const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const express = require('express');
const cookieParser = require('cookie-parser')();
const path = require("path");

const cors = require('cors')({
  origin: true
});
const app = express();

const gm = require("gm").subClass({
  imageMagick: true
});



app.use(cors);
app.use(cookieParser);
app.get('/hello', (req, res) => {
  // Location certificate template
  const tempLocalFile = path.resolve(
    __dirname,
    "certificateResources/TAU-Certificate.png"
  );
  const destinationFile = path.resolve(
    __dirname,
    "certificateResources/Destination.png"
  );

  gm(tempLocalFile).write(destinationFile, err => {
      if (err) {
        res.send(JSON.stringify(err));
      } else {
        res.send('OK')
      }
    });
});

// This HTTPS endpoint can only be accessed by your Firebase Users.
// Requests need to be authorized by providing an `Authorization` HTTP header
// with value `Bearer <Firebase ID Token>`.
exports.app = functions.https.onRequest(app);
```
