### ISSUE TITLE
Unexpected InvalidArgumentError

### ISSUE THREAD

**Issue by donmccurdy** [GoogleCloudPlatform/cloud-functions-emulator#138]
Given a small HTTP function:

```js
// function.js

/**
 * @param {Object} req Cloud Function request context.
 * @param {Object} res Cloud Function response context.
 */
exports.hexPrecipHttp = function hexPrecipHttp(req, res) {
  // ...
}
```

```
npm install -save-dev @google-cloud/functions-emulator
npx functions start
npx functions deploy hexPrecipHttp --trigger-http
```

Result:

```
ERROR: InvalidArgumentError: Invalid value 'hexPrecipHttp': Function name must contain only Latin letters, digits and a hyphen (-). It must start with letter, must not end with a hyphen, and must be at most 63 characters long.
    at new CloudFunction (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/@google-cloud/functions-emulator/src/model/cloudfunction.js:101:19)
    at Promise (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:309:29)
    at Controller._create (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:308:12)
    at client.getFunction.then (/Users/donmccurdy/.nvm/versions/node/v6.11.3/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:404:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Node.js v6.11.3, npm 5.4.0.

My JS file is named `function.js`, and marked as main in `package.json`. Anything I'm missing here? The function name seems to meet all requirements listed in the error message.

**Comment by louggl** [comment]
I am having this exact issue via [firebase functions](https://github.com/firebase/firebase-functions/issues/84#issuecomment-371971342).

**Comment by djaax** [comment]
I can confirm that @louggl 's solution works. I had the same problem with a Google internal firebase project.

Also, make sure to edit the correct file and to restart the emulator. Running `firebase serve --debug` (see above) should log the correct path to the emulator directory (most probably in the firebase-tools dir, not in the @ google-cloud dir).

**Comment by derek-baker** [comment]
@Sandeeprao69 did you resolve your issue?

**Comment by Sandeeprao69** [comment]
Hey @derek-baker,
Yes i was able to resolve this issue. I was using nvm with multiple node versions and function-emulator was installed on two diff node versions.

**Comment by dominikbulaj** [comment]
Hi,
I had same issue. I followed @louggl solution and I'm able to emulate (serve) functions locally. But since my ID has colon in name I see troubles deploying it to Firebase. Were you, guys, able to deploy your code in case your projectId had colons/comma in name?
