### ISSUE TITLE
Emulator fail to start

### ISSUE THREAD

**Issue by Leechael** [GoogleCloudPlatform/cloud-functions-emulator#145]
Got this:

```
$ functions start
Google Cloud Functions Emulator RUNNING
ERROR: TypeError: Cannot read property 'call' of undefined
    at Promise (/Users/leechael/.nvm/versions/node/v6.11.1/lib/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:34:42)
    at getService.then (/Users/leechael/.nvm/versions/node/v6.11.1/lib/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:33:16)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

My steps to install:
```
nvm install v6.11.1
nvm use v6.11.1
npm install -g @google-cloud/functions-emulator
```

Thanks!

**Comment by jmdobry** [comment]
I followed your steps, this is what I got:

```
$ nvm install v6.11.1
######################################################################## 100.0%
Checksums empty
Now using node v6.11.1 (npm v3.10.10)
$ nvm use v6.11.1
Now using node v6.11.1 (npm v3.10.10)
$ npm install -g @google-cloud/functions-emulator
/Users/jdobry/.nvm/versions/node/v6.11.1/lib
└─- @google-cloud/functions-emulator@1.0.0-alpha.26
$ functions start
Starting Google Cloud Functions Emulator...
Google Cloud Functions Emulator STARTED
No functions deployed ¯\_(ツ)_/¯. Run functions deploy --help for how to deploy a function.
$ functions status
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Google Cloud Functions Emulator                                                                                                                 │
├──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status           │ RUNNING                                                                                                                      │
│ ...              │ ...                                                                                                                          │
```

Please check out the [Troubleshooting Guide](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Troubleshooting)

If it doesn't help, please comment back on this issue with more details steps to reproduce your error.

**Comment by grayside** [comment]
I also encountered this problem.

`functions logs read` gave me the following output:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1218:7)
    at Object.readLogLines (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:33:39)
    at Controller.getLogs (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:462:10)
    at Object.exports.handler (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/src/cli/commands/logs/read.js:58:14)
    at Object.runCommand (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:1014:30)
    at Object.runCommand (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:195:96)
    at Object.parseArgs [as _parseArgs] (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:1014:30)
    at Object.parse (<...>/.nvm/versions/node/v6.11.5/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:542:25)
```

I tried #199 on the basis of the logging connection, but all I noticed is that the above log output stopped being generated.

node: 6.11.5

**Comment by ace-n** [comment]
Argh...I am now running into this problem too. @jmdobry where is the code that handles _writing_ logs - perhaps I can debug this locally?
