### ISSUE TITLE
Function logs read command fails when log file doesn't exist

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#147]
### Description

Somehow during an update of the emulator my log file disappeared, and when the `logs read` command is executed in this circumstance it fails

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.readLogLines (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:33:39)
    at Controller.getLogs (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:474:10)
    at Object.exports.handler (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/src/cli/commands/logs/read.js:58:14)
    at Object.self.runCommand (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:990:30)
    at Object.self.runCommand (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/lib/command.js:204:96)
    at Object.Yargs.self._parseArgs (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:990:30)
    at Object.Yargs.self.parse (/Users/jasonpolites/.nvm/versions/node/v6.11.2/lib/node_modules/@google-cloud/functions-emulator/node_modules/yargs/yargs.js:532:23)
```

### Steps to reproduce

```
$ rm $(functions status | grep 'Log file' | tr -s ' ' | cut -d' ' -f5)
$ functions logs read
```

Thanks!

**Comment by adamenger** [comment]
@jasonpolites I was able to fix this by touching the file given by `functions-emulator` status. By simply  recreating the empty file my `functions log read` ran successfully.

Still an issue but a workaround.

**Comment by techieshark** [comment]
Another workaround might be to run `functions logs clear`.

**Comment by danielrasmuson** [comment]
What worked for me was creating the logs file manually.

```
➜  run-function git:(prisma) ✗ fun logs clear
{ Error: ENOENT: no such file or directory, open '/Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.truncateSync (fs.js:848:15)
    at Object.clearLogs (/Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:72:10)
    at Controller.clearLogs (/Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:279:10)
    at Object.exports.handler (/Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/src/cli/commands/logs/clear.js:45:14)
    at Object.runCommand (/Users/danielrasmuson/.config/yarn/global/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/danielrasmuson/.config/yarn/global/node_modules/yargs/yargs.js:1014:30)
    at Object.runCommand (/Users/danielrasmuson/.config/yarn/global/node_modules/yargs/lib/command.js:195:96)
    at Object.parseArgs [as _parseArgs] (/Users/danielrasmuson/.config/yarn/global/node_modules/yargs/yargs.js:1014:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log' }
➜  run-function git:(prisma) ✗ touch /Users/danielrasmuson/.config/yarn/global/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log
➜  run-function git:(prisma) ✗ fun logs read
```

**Comment by mrdulin** [comment]
same issue.

```bash
{ Error: ENOENT: no such file or directory, open '/Users/ldu020/workspace/serverless-functions/node_modules/@google-cloud/functions-emulator/logs/cloud-functions-emulator.log'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.truncateSync (fs.js:803:15)
    at Object.clearLogs (/Users/ldu020/workspace/serverless-functions/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:72:10)
    at Controller.clearLogs (/Users/ldu020/workspace/serverless-functions/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:279:10)
    at Object.exports.handler (/Users/ldu020/workspace/serverless-functions/node_modules/@google-cloud/functions-emulator/src/cli/commands/logs/clear.js:45:14)
    at Object.runCommand (/Users/ldu020/workspace/serverless-functions/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/ldu020/workspace/serverless-functions/node_modules/yargs/yargs.js:1014:30)
    at Object.runCommand (/Users/ldu020/workspace/serverless-functions/node_modules/yargs/lib/command.js:195:96)
    at Object.parseArgs [as _parseArgs] (/Users/ldu020/workspace/serverless-functions/node_modules/yargs/yargs.js:1014:30)
    at Object.parse (/Users/ldu020/workspace/serverless-functions/node_modules/yargs/yargs.js:542:25)
```

**Comment by CryLittleSister** [comment]
I've taken this advice and touched the log file so I no longer get the error, however now nothing is being written to the log file

**Comment by waritthornnudee** [comment]
In my case I use node version v.6.16.0 and I change it to v.6.12.2(LTS) and the functions logs read work fine.

**Comment by gumatias** [comment]
Having the same issue. Log file not created, touching it didnt' help. I'm on node v8. Any ideas?

**Comment by gumatias** [comment]
Setting the log to another path worked.

```
functions config set logFile ~/Workspace/functions.log
functions restart
```
