### ISSUE TITLE
Issue when using NVM

### ISSUE THREAD

**Issue by rykerrumsey** [GoogleCloudPlatform/cloud-functions-emulator#160]
Currently using nvm to manage my node.js installations. 
Switched to node 6.11.1 to global install google-functions-emulator
Everything was installed and grpc_node was compiled successfully.

`functions start` produces

`{ Error: Cannot find module '/usr/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/src/grpc_extension.js:45:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
`

functions cannot find that module because its in my ~/.nvm dir
is there a way to change where the emulator looks for grpc_node?

**Comment by jmdobry** [comment]
> is there a way to change where the emulator looks for `grpc_node`?

No. The Emulator just does `require('grpc')` and the standard module lookup algorithm takes over.

Try:

1. `npm uninstall -g @google-cloud/functions-emulator`
1. `npm cache clean`
1. `npm install -g @google-cloud/functions-emulator`

**Comment by jmdobry** [comment]
Please check out the [Troubleshooting Guide](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Troubleshooting)

If it doesn't help, please comment back on this issue with more details steps to reproduce your error.
