### ISSUE TITLE
Unable to deploy locally anything using firestore document events (like onCreate)

### ISSUE THREAD

**Issue by psvensson** [GoogleCloudPlatform/cloud-functions-emulator#183]
I have tried for several days to in any way possible test a simple function which trigger onCreate. I finally tried to deploy it live, and it worked. So the code is OK. It looks like this;

const functions = require('firebase-functions');
...
exports.alldocs = functions.firestore.document('{collection}/{documentId}').onCreate((event) =>
{
  console.log('onCreate called for '+event)
  console.log(JSON.stringify(event))
});

When I have this code in my index.js and try to deploy it to the emulator (or any other function for that matter) I always get this message;

ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exists? Is there a syntax error in your code?
ERROR: Detailed stack trace: module.js:471
    throw err;
    ^

Error: Cannot find module '/media/peter/0c009e0d-b238-4b0f-b9c5-2641faf72c81/home/peter/projects/fbtest'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:40
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)

ERROR: Error: Failed to deploy function.
    at exec (/usr/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:135:18)
    at ChildProcess.exithandler (child_process.js:206:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

#### Environment details

  - OS: Linux Min 18
  - Node.js version: v6.12.3
  - npm version: 3.10.10
  - @google-cloud/functions-emulator version: 1.0.0-alpha.29

#### Steps to reproduce

  1. Paste above code in an index.js file 
  2. run functions deploy alldocs -H

Cheers;
PS

**Comment by isurufonseka** [comment]
Seeing this issue helped me, essentially if you have one or more oncreate functions the error that is displayed to you is not very informative. 

"ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exists? Is there a syntax error in your code?
ERROR: Detailed stack trace: module.js:471
throw err;
^"

Does not help you resolve the issue. Might be better to have a message along the lings of 

"OnCreate triggers are currently not supported"

**Comment by archelogos** [comment]
Make sure you don't have a main property in your package.json pointing to a non-existing file. That was the problem in my case.
Even using the functions cli to deploy the function and setting a valid local-path value, it seems it tries to always load it as a node package.

`  "main": "dist/index.js"`
