### ISSUE TITLE
Emulator doesn't work with node 10

### ISSUE THREAD

**Issue by CodingDoug** [GoogleCloudPlatform/cloud-functions-emulator#205]
- OS: OSX
  - Node.js version: 10.0.0 (via homebrew, compiled)
  - npm version: 5.6.0
  - @google-cloud/functions-emulator version: 1.0.0-beta.4

#### Steps to reproduce

I'm working with the Firebase CLI.  When I do `firebase serve --only functions` with node 10 in my path, I get the following error:

```
[2018-04-26T21:25:23.884Z] Error while deploying to emulator: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received 3272911701
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received 3272911701
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32LE (internal/buffer.js:515:3)
    at Buffer.writeInt32LE (internal/buffer.js:684:10)
    at Object.entryHeaderToBinary (/Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/adm-zip/headers/entryHeader.js:216:18)
    at Object.packHeader (/Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/adm-zip/zipEntry.js:260:39)
    at /Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/adm-zip/zipFile.js:198:41
    at Array.forEach (<anonymous>)
    at Object.compressToBuffer (/Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/adm-zip/zipFile.js:182:23)
    at Object.writeZip (/Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/adm-zip/adm-zip.js:454:32)
    at client.generateUploadUrl.then.then (/Users/dougstevenson/homebrew/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:168:13)
```

node 8.11.1 is OK.  Not sure if this is a firebase-tools or emulator issue, or perhaps adm-zip.

**Comment by reyou** [comment]
Same issue here. Any update on this?

**Comment by reyou** [comment]
For people who are having problem with similar error, I uninstalled node.js and installed latest stable release, and it started to work again.
I am getting following warning at command line, but it works.
> Warning: You're using Node.js v8.11.1 but Google Cloud Functions only supports v6.11.5.

**Comment by CodingDoug** [comment]
@reyou I've been using the emulator on node 8 for a long time.  It's node 10 that has a problem.  The general expectation is that you should be able to use other versions of node to test locally, as long as you aren't using language and runtime features that aren't available in the version of node running in Cloud Functions.  That's what the warning is for.

**Comment by championjared** [comment]
Additionally and related is that the documentation at https://cloud.google.com/functions/docs/emulator mentions the minimum version is >=6.11.1 which I tried to switch to after having the above error with v10, however when you install from yarn the minimum version is cited as >=6.11.5

**Comment by TheAmazingPT** [comment]
In other issues I read, that node v10.5.0 should fix this problem, since it was an internal problem within node v10. But I can't confirm it for myself running on node v10.5.0 :(
What about you?

**Comment by bio** [comment]
It works on node v10.5.0
```
firebase serve --only functions

i  functions: Preparing to emulate functions.
Warning: You're using Node.js v10.5.0 but Google Cloud Functions only supports v6.11.5.
i  functions: No HTTPS functions found. Use firebase functions:shell if you would like to emulate other types of functions.
```

**Comment by CodingDoug** [comment]
@bio It doesn't work - you didn't have any functions HTTP functions to emulate, so there was no opportunity for failure.  I still have problems with node 10.6.0, firebase-tools 3.19.3.

See also this for a workaround: https://github.com/firebase/firebase-tools/issues/770

**Comment by PatNeedham** [comment]
Inside [that if statement](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/blob/9f4b0fa66d6a35a129f0b79cef908865cbe48ac7/bin/emulator#L26) where it's logging the warning about using Node v7.0.0 or greater, would it be reasonable to execute a shell command there such as `which nvm` to see if nvm is installed on the machine?

And depending on whether it exists, log another line saying either "Please enter the following command to switch to the proper version: `nvm use v6.11.5`", or "Consider installing nvm on your machine to easily switch between Node versions: https://github.com/creationix/nvm"

**Comment by hgwood** [comment]
Some might find this useful as a workaround: `npx node@6.11.5 ./node_modules/firebase-tools/bin/firebase serve`.
