### ISSUE TITLE
Not supporting external NPM package dependencies

### ISSUE THREAD

**Issue by mikesparr** [GoogleCloudPlatform/cloud-functions-emulator#220]
I try to run a function that includes external dependencies in the `package.json` but they don't get installed and function won't run. This works fine on Gcloud, but when I try to use `functions deploy testFunction` from within the folder with the 2 files, it fails to deploy.

### Error stack
```
Warning: You're using Node.js v9.11.1 but Google Cloud Functions only supports v6.11.5.
ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exists? Is there a syntax error in your code?
ERROR: Detailed stack trace: internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'elasticsearch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/mike/Documents/Work/clienthub-cloud-functions/src/campaign/upsertCampaign/index.js:1:85)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

#### Environment details

  - OS: `10.13.5`
  - Node.js version: `v9.11.1`
  - npm version: `6.1.0`
  - @google-cloud/functions-emulator version: `1.0.0-beta.4`

#### Steps to reproduce

1. Create folder with `index.js` and `package.json` files
2. Add the following to package.json:
```
{
  "name": "sample-pubsub",
  "version": "0.0.1",
  "dependencies": {
    "elasticsearch": "^14.0.0",
    "uuid": "^3.1.0"
  }
}
```

3. Add the following to index.js:
```
const elasticsearch = require(`elasticsearch`);
const uuid = require('uuid/v1');

exports.testFunction = (event, callback) => {
  // The Cloud Pub/Sub Message object.
  const pubsubMessage = event.data;
  const messageStr = pubsubMessage.data ? Buffer.from(pubsubMessage.data, 'base64').toString() : null;
  const message = messageStr ? JSON.parse(messageStr) : {};
  const {request, campaign} = message;

  console.log({messageStr, message});

  callback();
}
```

4. `cd` to the folder and type `functions deploy testFunction`

**Comment by mikesparr** [comment]
It appears the emulator doesn't use the `package.json` file in the folder, but if I install the package dependencies locally then the deploy works. I had to add the trigger flag, but then it works.
