### ISSUE TITLE
functions deploy completely ignores --local-path

### ISSUE THREAD

**Issue by gberliner** [GoogleCloudPlatform/cloud-functions-emulator#314]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Check the [Emulator's docs](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki)
  - Check the Emulator's self-help: `functions --help` or `functions-emulator --help`
  - Search the issues already opened: https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - @google-cloud/functions-emulator version:

#### Steps to reproduce

  1. ???
  2. ???

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by gberliner** [comment]
[zzyzx@localhost firebase-functions-next-example]$ functions --version
1.0.0-beta.5

[zzyzx@localhost firebase-functions-next-example]$ functions deploy nextapp --entry-point app --local-path=./dist/functions/ --trigger-http
ERROR: Function load error: Code could not be loaded.
ERROR: Does the file exists? Is there a syntax error in your code?
ERROR: Detailed stack trace: module.js:471
    throw err;
    ^

Error: Cannot find module '/home/zzyzx/sandbox/firebase-functions-next-example'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:40
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)

ERROR: Error: Failed to deploy function.
    at exec (/home/zzyzx/.npm-global/lib/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:126:22)
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

[zzyzx@localhost firebase-functions-next-example]$ cd dist/functions/

[zzyzx@localhost functions]$ functions deploy nextapp --entry-point app --local-path=./dist/functions/ --trigger-http
Copying file:///tmp/tmp-23743CMIkJcS69x2r.zip...
Waiting for operation to finish...done.
Deploying function..........done.
Function nextapp deployed.
┌─────────────┬──────────────────────────────────────────────────────────────────────────┐
│ Property    │ Value                                                                    │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Name        │ nextapp                                                                  │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Entry Point │ app                                                                      │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Trigger     │ HTTP                                                                     │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Resource    │ http://localhost:8010/project-id-6454258612623283566/us-central1/nextapp │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Timeout     │ 60 seconds                                                               │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Local path  │ /home/zzyzx/sandbox/firebase-functions-next-example/dist/functions       │
├─────────────┼──────────────────────────────────────────────────────────────────────────┤
│ Archive     │ file:///tmp/tmp-23743CMIkJcS69x2r.zip                                    │
└─────────────┴──────────────────────────────────────────────────────────────────────────┘
[zzyzx@localhost functions]$ 

(notice i even left the bogus --local-path argument in there the second time; it ignored it, and only looked for index.js in current working directory!)

**Comment by gberliner** [comment]
accidentally closed..

**Comment by tsukakei** [comment]
Hi @gberliner ,  `--local-path` option doesn't exist anymore.
Instead, you can use `--source` ( or `-S`) option!
