### ISSUE TITLE
functions start fails (Module version mismatch)

### ISSUE THREAD

**Issue by gerhardcit** [GoogleCloudPlatform/cloud-functions-emulator#50]
### Description

After Installed on macOS with Node 6.9.5

### Steps to reproduce

`npm install -g @google-cloud/functions-emulator`
`functions start`

Error received.
```
functions start
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Any suggestions?
(I am using n to switch node versions. but installed it after switching to 6.9.5)

**Comment by gerhardcit** [comment]
Sorted.. Installed it at first with the wrong node version.
1. `npm uninstall -g @google-cloud/functions-emulator`, 
2. set node version with n
3. `npm install -g @google-cloud/functions-emulator`
