### ISSUE TITLE
First run after first install on fresh profile without Cloud SDK results in error

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#51]
### Description

On a completely fresh (MacOS) profile I installed a fresh version of the emulator, upon running just `functions` I get this:

```
 demo$ functions
Inferring project ID from Cloud SDK config. Speed up CLI commands by setting a project ID: functions config set projectId YOUR_PROJECT_ID or export GCLOUD_PROJECT=YOUR_PROJECT_ID
/bin/sh: gcloud: command not found
/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/utils/project.js:63
    throw new Error('Please provide a project ID: "functions config set projectId YOUR_PROJECT_ID" or "functions start --projectId YOUR_PROJECT_ID" or "export GCLOUD_PROJECT=YOUR_PROJECT_ID"');
    ^

Error: Please provide a project ID: "functions config set projectId YOUR_PROJECT_ID" or "functions start --projectId YOUR_PROJECT_ID" or "export GCLOUD_PROJECT=YOUR_PROJECT_ID"
    at module.exports.err (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/utils/project.js:63:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/options.js:26:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@google-cloud/functions-emulator/src/cli/commands/call.js:23:17)

```

I don't yet have gcloud installed, so I suspect this may be the cause (?)

**Comment by jmdobry** [comment]
And if you do as it says (`functions config set projectId YOUR_PROJECT_ID`) does it work after that? Or does the `gcloud: command not found` error persist?

**Comment by jmdobry** [comment]
I believe this has been fixed.
