### ISSUE TITLE
Block-scoped declarations error message

### ISSUE THREAD

**Issue by davidbielik** [GoogleCloudPlatform/cloud-functions-emulator#75]
### Description

Getting this error message after following the install instructions

```
$ functions start
/usr/local/lib/node_modules/@google-cloud/functions-emulator/bin/functions:62
let projectId = require('../src/utils/detectProjectId')(config.get('projectId'));
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

### Steps to reproduce
Installed via npm, then ran `functions start`. I'm on a mac

Thanks!

**Comment by jmdobry** [comment]
What version of Node.js are you using? The Emulator requires Node.js v6.9.1 or newer (because the production Google Cloud Functions service uses Node.js v6.9.1).

**Comment by davidbielik** [comment]
@jmdobry that was the issue, thanks 👍
